### ISSUE TITLE
Agregar nombre del dataset en el selector

### ISSUE THREAD

**Issue by abenassi** [datosgobar/infra.datos.gob.ar#39]
<img width="541" alt="Screenshot 2019-07-31 16 18 13" src="https://user-images.githubusercontent.com/4405346/62241196-16856380-b3af-11e9-87dc-8600a19e4461.png">

Que muestre tanto el id como el nombre:

`1 (Base de Series de Tiempo)`
`5 (Puntos Digitales)`

**Comment by lucaslavandeira** [comment]
Cerrado en #61
