### ISSUE TITLE
Diseñar los casos de uso de borrar distribuciones

### ISSUE THREAD

**Issue by abenassi** [datosgobar/infra.datos.gob.ar#66]
Casos de uso: 

+ Borrar una distribución por completo
+ Borrar versión actual de una distribución (la última guardada pasa a tomar su lugar)
+ Borrar una versión anterior

**Comment by floralonauta** [comment]
![wireframes-eliminar](https://user-images.githubusercontent.com/35771446/64988095-0fec7600-d8a1-11e9-9fb2-1b68b98657ae.jpg)
![wireframes-distribuciones-hover2-anteriores](https://user-images.githubusercontent.com/35771446/64988121-1b3fa180-d8a1-11e9-86fb-45d89fb5b77a.jpg)

**Comment by floralonauta** [comment]
el usuario puede eliminar una distribucion desde el icono de eliminar de la fila. Despues debera seleccionar (imagen 1) si desea borrarla completamente o solo la version actual.
En el caso de una version anterior, tambien aparece el icono de borrar, y en este caso solo borra la version. (Podemos mostrar un dialogo de "esta seguro que desea eliminar ..."
