### ISSUE TITLE
El upload de un catálogo falla al no registrar la "versión actual"

### ISSUE THREAD

**Issue by abenassi** [datosgobar/infra.datos.gob.ar#70]
![Screenshot 2019-08-22 11 03 30](https://user-images.githubusercontent.com/4405346/63521329-9ee9b680-c4cc-11e9-85fd-fc61d428fb7a.png)

**Comment by AWolfsdorf** [comment]
Estuvimos haciendo pruebas sobre este issue para intentar reproducirlo pero sin éxito, concluimos que esto debio pasar por datos que quedaron inconsistentes con versiones anteriores de la base de datos.
Por esta razon consideramos que este es un Non-Issue.
