### ISSUE TITLE
Centrar botones para elegir nodos en pantalla inicial

### ISSUE THREAD

**Issue by abenassi** [datosgobar/infra.datos.gob.ar#72]
![Screenshot 2019-09-04 09 43 49](https://user-images.githubusercontent.com/4405346/64255867-9d6eb400-cef8-11e9-9d3d-06e03da61b78.png)

**Comment by lucaslavandeira** [comment]
@floralonauta

Home/landing: 

Optamos por quedarnos con la implementación actual de botones por cada nodo (imagen) vs la propuesta en los wireframes (en donde se usa un selector para el nodo). Los usuarios rara vez estarán asociados a más de un nodo, entonces no nos pareció muy bueno meter el selector. Los administradores (nosotros) tendrían acceso a todos los nodos, pero no nos molestaría que sea muy "ruidoso" con tantos botones. 

Los botones de nodos estarían entrados, al estilo https://www.argentina.gob.ar/hacienda

**Comment by floralonauta** [comment]
![wireframes-1-02](https://user-images.githubusercontent.com/35771446/64987999-d9aef680-d8a0-11e9-9c8b-9ed7a9849ee9.jpg)

Cuando el usuario selecciona un nodo (card) queda marcado.
Cuando el usuario mas adelante desea cambiar de nodo se mostraria una vista similar a esta.

Duda:
 Si la mayoria de los usuarios tendrian un solo nodo, no podemos hacer que en esos casos no le muestre el paso de seleccionar nodo y entre directamente al nodo/catálogo?
otra duda: en el caso de los usuarios que tienen acceso a todos los nodos, cuantos serian? asi tambien contemplo ese caso en el diseño
