### ISSUE TITLE
Adecuar cabezal al diseño tal como está en argentina.gob.ar / poncho

### ISSUE THREAD

**Issue by abenassi** [datosgobar/infra.datos.gob.ar#73]
El banner aplica a todas las pantallas.

![Screenshot 2019-09-04 09 49 21](https://user-images.githubusercontent.com/4405346/64256222-6351e200-cef9-11e9-8955-0d444f07bbff.png)

**Comment by lucaslavandeira** [comment]
@floralonauta 

Dos cosas en detalle: 
- breadcrumbs
- Obviamos el nombre completo del catálogo, nos vamos a quedar solo con el ID por ahora. El ID son strings cortitos al estilo "sspm", "modernizacion".

**Comment by floralonauta** [comment]
![wireframes-distribuciones-1](https://user-images.githubusercontent.com/35771446/64987937-b3895680-d8a0-11e9-9073-afa47dd68714.jpg)
