### ISSUE TITLE
Adecuar estilos de "Agregar catálogo"

### ISSUE THREAD

**Issue by abenassi** [datosgobar/infra.datos.gob.ar#74]
![Screenshot 2019-09-04 09 55 28](https://user-images.githubusercontent.com/4405346/64256639-3eaa3a00-cefa-11e9-9b5c-69a7298049aa.png)

**Comment by lucaslavandeira** [comment]
@floralonauta 

Preferimos que sea una vista aparte, más que un modal. El diseño sería igual, sólo que adaptado para usar la pantalla entera y no estar contenido completamente en el modal.

**Comment by floralonauta** [comment]
ahora aparece en la misma pantalla, centrado, en vez de en un modal.
Se aplico el mismo criterio a las vistas de agregar distribución para tener consistencia.
![wireframes-nuevo-cat](https://user-images.githubusercontent.com/35771446/64987884-8e94e380-d8a0-11e9-85a3-10e9c1f70261.jpg)
![wireframes-1-06](https://user-images.githubusercontent.com/35771446/64987901-9ce2ff80-d8a0-11e9-995c-c2573c16951b.jpg)
