### ISSUE TITLE
Eliminar sección "archivos actuales" y reemplazar por íconos en la landing de nodo

### ISSUE THREAD

**Issue by abenassi** [datosgobar/infra.datos.gob.ar#76]
![Screenshot 2019-09-04 10 06 31](https://user-images.githubusercontent.com/4405346/64257443-bf1d6a80-cefb-11e9-9c3a-f6a15de32152.png)

Se agregan 4 íconos:

+ XLSX / JSON cuando se hace click descargan el catálogo o lo muestran en el browser
+ Cada uno tiene además un "Copiar URL" que permite copiar al portapapeles la URL, y que tiene un hoover con la URL que va a ser copiada

**Comment by lucaslavandeira** [comment]
@floralonauta 

El modal que se abre en "archivos actuales" lo ponemos en esta misma vista, arriba de los íconos de ver distribuciones, subir nueva versión, y ver historial. Sería deseable un botón de descarga, y un botón de "copiar link" tanto para la versión JSON como la XLSX de los archivos actuales

**Comment by floralonauta** [comment]
![wireframes-1-03](https://user-images.githubusercontent.com/35771446/64987810-60170880-d8a0-11e9-93a8-b80e3f6a259d.jpg)
