### ISSUE TITLE
Poner primero el manejo del catálogo antes que el de las distribuciones

### ISSUE THREAD

**Issue by abenassi** [datosgobar/infra.datos.gob.ar#77]
![Screenshot 2019-09-04 10 10 27](https://user-images.githubusercontent.com/4405346/64257760-479c0b00-cefc-11e9-8213-c876970c38c9.png)

**Comment by lucaslavandeira** [comment]
@floralonauta 

Cambio de orden de los íconos. Quedaría de izquierda a derecha: Subir nueva versión, Ver historial, Ver distribuciones

**Comment by floralonauta** [comment]
![wireframes-1-03](https://user-images.githubusercontent.com/35771446/64987727-32ca5a80-d8a0-11e9-81e2-a1cd7f87a10c.jpg)
