### ISSUE TITLE
Re-diseño de la pantalla de distribuciones, y diseño de nueva pantalla faltante

### ISSUE THREAD

**Issue by abenassi** [datosgobar/infra.datos.gob.ar#78]
![Screenshot 2019-09-04 10 24 07](https://user-images.githubusercontent.com/4405346/64258773-3522d100-cefe-11e9-9b52-ee2fdd598e13.png)

+ Habría que re-diseñar esta pantalla
+ Sumar diseño de la pantalla que permite (a) subir nueva distribución y (b) ver y descargar las versiones anteriores.

**Comment by lucaslavandeira** [comment]
@floralonauta 

El segundo ítem implica una nueva vista, parecida a la de historial del catálogo, con las versiones viejas en una tabla (en este caso de una sola columna)

**Comment by floralonauta** [comment]
En el nuevo diseño, cuando el usuario pasa sobre una fila (distribución) se habilitan mas acciones (copiar link, eliminar y ver versiones anteriores). La opción de descargar esta siempre visible. 
- Si copia el link le aparece un cartelito que dice "vinculo copiado al portapapeles" (en invision quedo mal situado, pero es solo para mostrar el concepto)
- Si elimina la distribucion aparece un modal que le pregunta si quiere eliminar esta version o todo.
- Si selecciona el icono de ver versiones anteriores aparece la vista nueva, donde a su vez, el usuario puede eliminar o copiar el link de una versión.

Los iconos de los botones de acciones secundarias se pueden reemplazar por texto. El mismo puede aparecer en hover o estar siempre visible. Todo también depende de la periodicidad o probabilidad de ejecutar esas acciones.
![wireframes-distribuciones-1](https://user-images.githubusercontent.com/35771446/64987636-fb5bae00-d89f-11e9-8a61-43d9b45e35f5.jpg)
![wireframes-distribuciones-hover2](https://user-images.githubusercontent.com/35771446/64987679-18907c80-d8a0-11e9-915b-2c1a40fde5fb.jpg)

**Comment by floralonauta** [comment]
![wireframes-1-17](https://user-images.githubusercontent.com/35771446/64987777-4e356580-d8a0-11e9-8359-1bedfdc3e198.jpg)
